name: Test

#
# Test strategy
# 
# - unit-test:        Run all tests on latest macOS and Xcode.
# - unit-test-linux:  Run tests on Linux (Swift 5.1) - Not include the Combine extension tests.
# - integration-test: Run integration test by Xcode 11.3.1 and Swift 5.1.3 with CocoaPods.
#

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Unit Test
      run: make test

    - name: Convert coverage file
      run: |
        xcrun llvm-cov export \
            .build/debug/SwiftPrettyPrintPackageTests.xctest/Contents/MacOS/SwiftPrettyPrintPackageTests \
            -instr-profile .build/debug/codecov/default.profdata \
            -ignore-filename-regex=".build|Tests" \
            -format="lcov" > info.lcov

    - name: Upload to codecov.io
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  unit-test-linux: # Not include Combine extension tests
    runs-on: ubuntu-latest
    container: swift:5.1

    steps:
    - uses: actions/checkout@v2

    - name: Run Unit Test
      run: make test

  integration-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode 11.3.1
      run: sudo xcode-select -s '/Applications/Xcode_11.3.1.app'

    - name: Cache bundler
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundler-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          bundler-${{ hashFiles('Gemfile.lock') }}

    - name: Bundle install
      run: |
        bundle

    - name: Run Integration Test
      run: |
        make integration-test
